rabbitmq:
  url: 'amqp://localhost'

logger:
  console:
    level: 'silly'

store:
  rabbitmq:
    url: 'amqp://localhost'
    exchange: 'deepbreath'
    queue: 'store'
    prefetch: 10
  database:
    url: '' # set in local.yaml
  webserver:
    port: 8081 # overwritten in environment specific file
    hostname: 'localhost' # overwritten in environment specific file
    childs: 2
  stations:
    nearest:
      limit: 10
      distance: 300000

mobile:
  webserver:
    port: 8080 # overwritten in environment specific file
    hostname: 'localhost' # overwritten in environment specific file
    childs: 2

  parameter_groups:
    - code: 'air_quality'
      name: 'Jakość powietrza'
      parameters:
        - co
        - pm10
        - pm2.5
        - bzn
        - o3
        - so2
        - no2
        - no
        - nox
        - pb
        - tln
        - oxy
        - mpxy
        - ebzn
        - pm10_as
        - pm10_bap
        - pm10_cd
        - pm10_ni
        - pm10_pb

    - code: 'weather'
      name: 'Dane pogodowe'
      parameters:
        - temp
        - rain
        - humid
        - press
        - ws
        - wd
        - rad

aqi:
  webserver:
    port: 8082 # overwritten in environment specific file
    hostname: 'localhost' # overwritten in environment specific file
    childs: 2

datasource:
  dacsystem:
    origins:
      - code: 'pl-wielkopolskie'
        rabbitmq:
          queue: 'datasource.pl-wielkopolskie'
          pattern: 'datasource:pl-wielkopolskie'
        api:
          host: 'powietrze.poznan.wios.gov.pl'

      - code: 'pl-zachodniopomorskie'
        rabbitmq:
          queue: 'datasource.pl-zachodniopomorskie'
          pattern: 'datasource:pl-zachodniopomorskie'
        api:
          host: 'powietrze.wios.szczecin.pl'

      - code: 'pl-lubuskie'
        rabbitmq:
          queue: 'datasource.pl-lubuskie'
          pattern: 'datasource:pl-lubuskie'
        api:
          host: '80.53.180.198'

      - code: 'pl-slaskie'
        rabbitmq:
          queue: 'datasource.pl-slaskie'
          pattern: 'datasource:pl-slaskie'
        api:
          host: 'powietrze.katowice.wios.gov.pl'

      - code: 'pl-dolnoslaskie'
        rabbitmq:
          queue: 'datasource.pl-dolnoslaskie'
          pattern: 'datasource:pl-dolnoslaskie'
        api:
          host: 'air.wroclaw.pios.gov.pl'

      - code: 'pl-malopolskie'
        rabbitmq:
          queue: 'datasource.pl-malopolskie'
          pattern: 'datasource:pl-malopolskie'
        api:
          host: 'monitoring.krakow.pios.gov.pl'

      - code: 'pl-opolskie'
        rabbitmq:
          queue: 'datasource.pl-opolskie'
          pattern: 'datasource:pl-opolskie'
        api:
          host: 'www.opole.pios.gov.pl'
          port: 81

      - code: 'pl-podkarpackie'
        rabbitmq:
          queue: 'datasource.pl-podkarpackie'
          pattern: 'datasource:pl-podkarpackie'
        api:
          host: 'stacje.wios.rzeszow.pl'

    api:
      paths:
        stations: '/stacje/aktywne'
        configuration: '/dane-pomiarowe/wczytaj-konfiguracje'
        measurements: '/dane-pomiarowe/pobierz'
      ratelimit: 500
      retries: 10

    rabbitmq:
      url: 'amqp://localhost'
      exchange: 'deepbreath'

    measurements:
      update_interval: 300000 # 5 mins

    configuration:
      cache_ttl: 3600000 # 1 hour

    stations:
      cache_ttl: 3600000 # 1 hour

    redis:
      host: 'localhost'
      port: 6379
      prefix: '' # set in environment specific file

    health:
      interval: 1800000
