rabbitmq:
  url: 'amqp://localhost'

logger:
  console:
    level: 'silly'

store:
  rabbitmq:
    url: 'amqp://localhost'
    exchange: 'deepbreath'
    queue: 'store'
    prefetch: 10
  database:
    url: '' # set in local.yaml
  webserver:
    port: 8081 # overwritten in environment specific file
    hostname: 'localhost' # overwritten in environment specific file
    childs: 2
  stations:
    nearest:
      limit: 10
      distance: 300000

mobile:
  webserver:
    port: 8080 # overwritten in environment specific file
    hostname: 'localhost' # overwritten in environment specific file
    childs: 2

  parameter_groups:
    - code: 'air_quality'
      name: 'Jakość powietrza'
      parameters:
        - co
        - pm10
        - pm10_as
        - pm10_bap
        - pm10_cd
        - pm10_ni
        - pm2.5
        - no
        - no2
        - nox
        - so2
        - o3
        - bzn

    - code: 'weather'
      name: 'Dane pogodowe'
      parameters:
        - temp
        - humid
        - press
        - ws
        - wd

aqi:
  webserver:
    port: 8082 # overwritten in environment specific file
    hostname: 'localhost' # overwritten in environment specific file
    childs: 2

datasource:
  pl-wielkopolskie:
    api:
      host: 'powietrze.poznan.wios.gov.pl'
      paths:
        stations: '/'
        configuration: '/dane-pomiarowe/wczytaj-konfiguracje'
        measurements: '/dane-pomiarowe/pobierz'
      ratelimit: 500
      retries: 10

    rabbitmq:
      url: 'amqp://localhost'
      exchange: 'deepbreath'
      queue: 'datasource.pl-wielkopolskie'

    measurements:
      update_interval: 300000 # 5 mins

    configuration:
      cache_ttl: 3600000 # 1 hour

    stations:
      cache_ttl: 3600000 # 1 hour

    redis:
      host: 'localhost'
      port: 6379
      prefix: '' # set in environment specific file

    health:
      interval: 1800000