datasource:
  pl-wielkopolskie:
    redis:
      host: 'localhost'
      port: 6379
      prefix: 'deep-breath:pl-wielkopolskie:'

store:
  webserver:
    port: 8081
    hostname: 'localhost'

mobile:
  webserver:
    port: 8080
    hostname: 'localhost'

  store:
    hostname: 'localhost'
    port: 8081

