datasource:
  pl-wielkopolskie:
    redis:
      host: 'localhost'
      port: 6379
      prefix: 'deep-breath:tst:pl-wielkopolskie:'

store:
  webserver:
    port: 8091
    hostname: 'localhost'

mobile:
  webserver:
    port: 8090
    hostname: 'localhost'

  store:
    hostname: 'localhost'
    port: 8091

